name: envs
channels:
  - defaults
dependencies:
  - pip:
      - asttokens==2.4.1
      - attrs==23.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - branca==0.7.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - colorcet==3.1.0
      - cssselect==1.2.0
      - cycler==0.12.1
      - decorator==5.1.1
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - filelock==3.14.0
      - fonttools==4.51.0
      - folium==0.16.0
      - greenlet==3.0.3
      - hvplot==0.9.2
      - idna==3.7
      - ipython==8.24.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - kiwisolver==1.4.5
      - lxml==5.2.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.3
      - nltk==3.8.1
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pillow==10.3.0
      - prompt-toolkit==3.0.43
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyviz-comms==3.0.2
      - pyyaml==6.0.1
      - regex==2024.4.28
      - requests==2.31.0
      - requests-file==2.0.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - six==1.16.0
      - soupsieve==2.5
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - sympy==1.12
      - threadpoolctl==3.5.0
      - tldextract==5.1.2
      - tqdm==4.66.2
      - traitlets==5.14.3
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
